[Driver]

browser = "firefox"
data_dir = "/tmp/butterbee"

[Capabilities]

# always_match = {
#   acceptInsecureCerts = false,
#   browserName = "firefox",
#   browserVersion = "141.0",
#   platformName = "linux",
# }

[Browsers.firefox]

# TODO: doesn't work
host = "127.0.0.1"
port_range = [9222, 9242]
