name = "butterbee"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.2.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
stratus = { git = "https://github.com/rawhat/stratus.git", ref = "a7f6db2716862aebd842bfcf0216b28b9d92079c" }
# stratus = ">= 1.0.2 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
youid = ">= 1.5.1 and < 2.0.0"
glam = ">= 2.0.3 and < 3.0.0"
birl = ">= 1.8.0 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
logging = ">= 1.3.0 and < 2.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck_gleeunit_utils = { git = "https://github.com/varnerac/qcheck_gleeunit_utils", ref = "main"}
