name = "butterlib"
version = "1.0.0"

description = "Helper functions for butterbidi and butterbee"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
