name = "butterbidi"
version = "1.0.1"

description = "Spec compliant webdriver bidi types, decoders and encoders for gleam"

licences = ["Apache-2.0"]

[repository]
type = "codeberg"
user = "gelei"
repo = "butterbee"

[[links]]
title = "github mirror"
href = "https://github.com/Damnjelly/butterbee"

[[documentation.pages]]
title = "changelog"
path = "changelog.html"
source = "CHANGELOG.md"

internal-modules = ["internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
palabres = ">= 1.0.2 and < 2.0.0"
