name = "butterbidi"
version = "0.1.0"

description = "A webdriver bidi cilent written in Gleam, for Gleam."

licences = ["Apache-2.0"]

repository = { type = "codeberg", user = "gelei", repo = "butterbee" }

links = [
	{ title = "github mirror", href = "https://github.com/Damnjelly/butterbee" },
]

target = "erlang"

internal-modules = ["internal/*"]

[dependencies]
butterlib = { path = "../butterlib" }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
youid = ">= 1.5.1 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
