name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./butterbee
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "latest"
      - uses: nanasess/setup-chromedriver@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "latest"
          gleam-version: "latest"
          rebar3-version: "latest"
      - run: gleam deps download
      - run: xvfb-run -a gleam test
      - run: gleam format --check src test
