name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: 'latest'
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: xvfb-run -a gleam test
      - run: gleam format --check src test
